version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate && gunicorn app.wsgi:application -b 0.0.0.0:8000"
    environment:
      - DB_URL=postgres://logs:secretpassword@db/apache_logs
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=apache_logs
      - POSTGRES_USER=logs
      - POSTGRES_PASSWORD=secretpassword

  redis:
    image: redis:5-alpine
