# Generated by Django 2.2 on 2020-03-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, default='', max_length=15, verbose_name='IP адрес')),
                ('date', models.DateTimeField(db_index=True, null=True, verbose_name='Дата и время')),
                ('method', models.CharField(max_length=6, verbose_name='HTTP метод')),
                ('path', models.CharField(default='', max_length=255, verbose_name='Путь')),
                ('response_code', models.SmallIntegerField(null=True, verbose_name='Код ответа')),
                ('response_size', models.IntegerField(null=True, verbose_name='Размер ответа')),
                ('user_agent', models.CharField(max_length=255, null=True, verbose_name='Агент')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'ordering': ('date',),
            },
        ),
    ]
