# Generated by Django 2.2 on 2020-03-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parsing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('url', models.URLField()),
                ('content_length', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Парсинг',
                'verbose_name_plural': 'Парсинг',
                'ordering': ('-started_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='accesslog',
            options={'ordering': ('-date',), 'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
    ]
